# The first line refers to the version 1.2 of the .dockstore.yml schema
version: 1.2

# An array of workflows. Each element corresponds to a workflow on Dockstore.
workflows:

# The optional workflow name for a workflow, which may only consist of alphanumerics
  # and internal underscores and hyphens, but no spaces or other characters. Names may not exceed 256 characters.
  # If using a .dockstore.yml with multiple workflows, this field is required
  # to uniquely identify workflows in the repository.
  #
  # It should be noted that having the name come first is an arbitrary decision.
  # You could use subclass instead, for instance. Provided arrays are not broken
  # up, the order of fields within a .dockstore.yml is not important.
  - name: WholeGenomeGermlineSingleSample
  # The descriptor language used for the workflow. CWL, WDL, NFL (Nextflow), or GALAXY.
  # This cannot be changed once the workflow is registered.
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl

  - name: VariantCalling
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/pipelines/broad/dna_seq/germline/variant_calling/VariantCalling.wdl

  - name: DNASeqStructs
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/structs/dna_seq/DNASeqStructs.wdl
  - name: AggregatedBamQC
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/AggregatedBamQC.wdl
  - name: Alignment
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/Alignment.wdl
  - name: BamProcessing
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/BamProcessing.wdl
  - name: BamToCram
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/BamToCram.wdl 
  - name: DragenTasks
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/DragenTasks.wdl
  - name: DragmapAlignment
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/DragmapAlignment.wdl
  - name: GermlineVariantDiscovery
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/GermlineVariantDiscovery.wdl 
  - name: Qc
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/Qc.wdl
  - name: SplitLargeReadGroup
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/SplitLargeReadGroup.wdl
  - name: UnmappedBamToAlignedBam
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/UnmappedBamToAlignedBam.wdl
  - name: Utilities
    subclass: WDL
    primaryDescriptorPath: /WholeGenomeGermlineSingleSample_v3.1.6/tasks/broad/Utilities.wdl
