version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: https://github.com/UW-GAC/gregor_wgs_processing/blob/main/WholeGenomeGermlineSingleSample_v3.1.6/pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl
    authors:
      - name: Marsha Wheeler
        email: mmwheel@uw.edu
    topic: WholeGenomeGermlineSingleSample
