version: 1.2
    workflows:
        - subclass: WDL
          primaryDescriptorPath: https://github.com/UW-GAC/gregor_wgs_processing/edit/main/WholeGenomeGermlineSingleSample_v3.1.6/  # absolute path
          testParameterFiles: <String Array>  # absolute path
          readMePath: <String> # absolute path
          authors:
              - name: marsha wheeler
                email: mmwheel@uw.edu
